[supabase]
url = "https://btigfsobvmqczpinxhrk.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ0aWdmc29idm1xY3pwaW54aHJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5MTA3NDcsImV4cCI6MjA1ODQ4Njc0N30.8-e5OZBIsgExZwpWBrscQ9UMq-SZdfAPshEU0yR-C74"